name: Build Example

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0

      - name: npm install
      - run: npm install

      - name: build
      - run: npm run build --if-present

      - name: test
      - run: npm test

      - name: Better Test Reports Action
  # You may pin to the exact commit or the version.
  # uses: mridang/action-test-reporter@720c9c56f73e527681bcb30c33da4ccd62bf70fb
        uses: mridang/action-test-reporter@v1.3.0
        with:
    # GitHub token used to authenticate API requests. Required for checking status checks and publishing releases. Use `secrets.GITHUB_TOKEN` or a PAT with elevated scopes if needed.

          github-token: secrets.GITHUB_TOKEN
# The directory where your project is located, used as the base for making file paths in the report relative.

          working-directory: /
          # The path to the single code coverage report file you want to parse (e.g., 'build/reports/clover.xml').
      
          coverage-file: false
          # Set to `true` to upload the generated coverage report as a workflow artifact. If omitted or left empty, this defaults to `true`. Set to `false` to disable artifact upload.
      
          upload-coverage-report: false
                
          
