name: Build Example

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0

      - name: npm install
      - run: npm install

      - name: build
      - run: npm run build --if-present

      - name: test
      - run: npm test

      - name: Better Test Reports Action
        uses: mridang/action-test-reporter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./
          coverage-file: ./reports/clover.xml
          upload-coverage-report: true
                
          
